### ISSUE TITLE
Cairo SVG diagrams created with Windows Dia have partially white/transparent background

### ISSUE THREAD

**Issue by SicroAtGit** [Fossy-Cats/Git-Buch_EN#31] opened 2021-10-26 18:28 UTC
I noticed that the Cairo SVG diagrams created with the Windows version of Dia have a white box as a background, but it does not fill the entire background, making the unfilled background transparent.

To have a quick look at what I mean, [switch to a dark theme in GitHub](https://github.com/settings/appearance) (for example, the "Dark dimmed" theme that I use) and look at [the diagrams](https://github.com/Fossy-Cats/Git-Buch_EN/tree/master/assets_src/img/dia#commit-graphsvg).

Cairo SVG diagrams created with the Linux version of Dia, have a white box that always fills the entire background, but they unfortunately have the black border, around the entire SVG.

It's not a big problem because we have a white background in the GitBook anyway, but does the box have any purpose? If not, we should remove the "erroneous" box from the diagrams.

**Comment by SicroAtGit** [comment] 2021-10-30 12:28
> Without these outer boxes the diagrams will look strange (one bigger than the other) and without any padding around them

I just removed the white box from the diagram `docs_src/images/commit-graph.svg` with Inkscape and then viewed `docs_src/GitBook_Preview.html` in Firefox. The diagram is still in the same position and has the same padding, which means that removing the box has no negative effect and the box is not the box responsible for centering the diagram correctly.

**Comment by tajmone** [comment] 2021-10-30 12:38
But then diagrams of a same series with different widths will look out of proportion.

**Comment by tajmone** [comment] 2021-10-30 13:53
# Added Previewer

I've now added a Bash script to auto-generate a special HTML page to preview all generated SVGs against a checkered background in order to clearly see their outbox, transparency, etc. Need to run the script once to generate the page, or every time a new SBV is added to the folder (but no need to re-generate if rebuilding the SVGs, since it loads them from disk).

Now I'll start experimenting previews, by removing the SVGO optimization step, and see if that's the problem. Then I'll go over all the Dia sources again, to fix boxes, etc. Maybe not today, but I'll do some tests at least, to begin.

**Comment by tajmone** [comment] 2021-10-30 16:23
# Box Sixe Problem Solved

I've managed to discover why some background boxes are not being rendered in the correct size: it's because their top left angle is not aligned to coordinates **0.0**. It looks like Dia (or the exporter) is buggy when handling negative coordinates.

So, now I'm re-aligning all the BG Boxes to 0.0, and the diagrams inside them. This solves one problem.

But you're right, the background is being painted white, even though it's set to be undrawn! I have no idea how to fix this. Let's just hope everyone uses white background for now, so we can have the diagrams aligned properly.

It doesn't look like SVGO had anything to do with either problem though, since I've tried rebuilding the diagrams by skipping the optimization part and the results are the same.

**Comment by tajmone** [comment] 2021-10-30 17:29
# Fixed

@SicroAtGit, I've polished all diagrams all over again. Quite a few needed re-aligning their BG box to 0:0, but for others I had already done that (not knowing it was so important). Now you can see in the dedicated HTML preview page that the background boxes are consistent with their diagram, and all in white.

I've removed quite a few empty text boxes and labels, which I believe were there due to cut and copy operations (i.e. pasting sample elements when starting a new diagram from scratch).

I only found one diagram which was using a generic font (_Monospace_), so I hope that there are none left now (most of them were actually empty labels).

So I'm closing this issue, for we should consider all diagrams polished now.

As for the transparency of the BG Box, I actually think that I was aware that it wouldn't be transparent in the final image, but since the border was not being shown I was happy with it. IRR, other export options and/or Dia version could preserve the BG transparency, but would paint its border in black, so I believe we ultimately settled with this arrangement. Anyhow, for now having a white BG is OK, in the future we'll see.

And ... **YES _WE NEED_ THE BG BOXES!!!** If you look closely at the [Rebase Images Group] you'll remember why we need it with the SVG format, otherwise we can't control the proportions of similar images:

![rebase-before.svg](https://raw.githubusercontent.com/Fossy-Cats/Git-Buch_EN/master/docs_src/images/rebase-before.svg)


-------------------------------------------------------------------------------

![rebase-after.svg](https://raw.githubusercontent.com/Fossy-Cats/Git-Buch_EN/master/docs_src/images/rebase-after.svg)

As you can see, these two comprise a series of before/after image, so they need to be same-width and same in-image alignment of the common elements — none of which can be achieved without a BG box with identical width in both images.

[Rebase Images Group]: https://github.com/Fossy-Cats/Git-Buch_EN/tree/master/assets_src/img/dia#images-group-rebase

**Closed by tajmone** 2021-10-30 17:29 UTC
Labels: :hammer: Dia, :star: diagrams

**Comment by SicroAtGit** [comment] 2021-10-30 21:50
Very good work!

> Anyhow, for now having a white BG is OK, in the future we'll see.

Yes, that's okay. I'll check tomorrow if there is already an issue created for it in the Dia repository. If not, I will create one.

> **YES _WE NEED_ THE BG BOXES!!!**

Sure, I didn't claim otherwise. Above I wrote that I assumed that the white box is another box, so not the box that is responsible for the correct centering. But obviously my quick test was not sufficient after I removed the white box.

**Comment by tajmone** [comment] 2021-10-31 00:15
> Sure, I didn't claim otherwise. Above I wrote that I assumed that the white box is another box, so not the box that is responsible for the correct centering. But obviously my quick test was not sufficient after I removed the white box.

😜 It's just that these diagrams have turned out into a nightmare. Sure, it was a great chance to learn more about Dia, but let's hope that now they're good.

**Comment by SicroAtGit** [comment] 2021-10-31 10:05
Yes, I hope so too.

Bug reported in the Dia repository: [Cairo SVG export: Transparent background is colored white](https://gitlab.gnome.org/GNOME/dia/-/issues/511)

**Comment by tajmone** [comment] 2021-10-31 17:00
Thanks. I guess the problem is due to an internal lack of support of `transparent` as a color value, so the don't draw BG directive probably only works in some output formats. IRC, Dia tries to stick to the basic SVG standard, in order to ensure that the generated images will be viewable on any tool that supports SVG.

The SVG standard is quite huge, and it's actually a set of different standards, not just one. So ensuring full support of all SVG features can be tricky. 

E.g. yesterday I've experimented creating an executable eBook from the ALAN Manual, using a new Asciidoctor chunker tool that splits the single document into chapters. The eBook software uses the IE Trident engine (WebControl) to show HTML contents, so it has limited support for CSS3, HTML5 and SVG. But all the Dia SVG diagrams are showing correctly, because Dia sticks to SBG baseline standard.
